import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/widgets/sidebar";
import localFont from "next/font/local";

const pretendardFont = localFont({
  src: "./PretendardVariable.woff2",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendardFont.className}>
      <body className="flex flex-row">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
