import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/widgets/sidebar";
import localFont from "next/font/local";
import { Header } from "@/widgets/header";
import { RecentlyUpdatedPostList } from "@/widgets/recentlyUpdatedPostList";
import { TrendingTagList } from "@/widgets/trendingTagList";
import { ScrollToTopButton } from "@/features/scrollToTop";
import { Footer } from "@/widgets/footer";

const pretendardFont = localFont({
  src: "./PretendardVariable.woff2",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "노현진's Blog",
    template: "%s | 노현진's Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={pretendardFont.className}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function () {
              try {
                const theme = localStorage.getItem("theme");

                if (theme === "dark") {
                  document.documentElement.classList.add("dark");
                }
              } catch (e) {}
            })();`,
          }}
        />
      </head>
      <body className="flex flex-row">
        <Sidebar />
        <div className="flex w-full flex-col pr-7 pl-75">
          <Header />
          <div className="mt-12 flex w-full flex-row justify-between gap-8 pl-6">
            <div className="flex w-full min-w-0 flex-col gap-12">
              {children}
              <Footer />
            </div>
            <div className="flex w-70 flex-col gap-16">
              <RecentlyUpdatedPostList />
              <TrendingTagList />
            </div>
          </div>
          <aside className="fixed right-20 bottom-15">
            <ScrollToTopButton />
          </aside>
        </div>
      </body>
    </html>
  );
}
