import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/widgets/sidebar";
import localFont from "next/font/local";
import { Header } from "@/widgets/header";
import { RecentlyUpdatedPostList } from "@/widgets/recentlyUpdatedPostList";

const pretendardFont = localFont({
  src: "./PretendardVariable.woff2",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "노현진's Blog",
    template: "%s | 노현진's Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={pretendardFont.className}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function () {
              try {
                const theme = localStorage.getItem("theme");

                if (theme === "dark") {
                  document.documentElement.classList.add("dark");
                }
              } catch (e) {}
            })();`,
          }}
        />
      </head>
      <body className="flex flex-row">
        <Sidebar />
        <div className="flex w-full flex-col px-3">
          <Header />
          <div className="mt-12 flex w-full flex-row justify-between px-8">
            {children}
            <div className="flex min-w-70 flex-col">
              <RecentlyUpdatedPostList />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
